name: workspaces

on: [push, pull_request]

jobs:
  workspaces:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04] #, macos-latest, windows-latest]

    name: Build workspace on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal --no-self-update

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - name: Check
        run: cargo check
      
      - name: Build
        run: cargo build --verbose --all
