name: workspaces

on: [push, pull_request]

jobs:
  workspaces:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build workspace on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal --no-self-update

      - uses: ./

      - run: |
          cargo check
          cargo build --release
